### ISSUE TITLE
missing file SoapySDR/ConverterRegistry.hpp

### ISSUE THREAD

**Issue by ghost** [petrinm/SoapyShared#5]
I am using Debian Buster with the soapy packages and -dev installed from Debian repository.  It is version 0.6
When compiling SoapyShared I get an error:
fatal error: SoapySDR/ConverterRegistry.hpp: No such file or directory
other files are available in /usr/include/SoapySDR

Does this package require version 0.7 of SoapySDR or is it likely that I need to install another package that brings that file?

**Comment by petrinm** [comment]
Hi @pe1chl,
I haven't pay much attention which are the version requirements for plugin but looks like Soapy's type converters are supported starting from version 0.7. Nevertheless, the code doesn't use converters atm. The Soapy's converters are planned to be used for converting between different streams to avoid need to force data types always to floats (CF32). This part of the code is not active atm and I made a commit 5cb7d58 to address this issue for now.
Please note, that this plugin is still under development and there's like more issues like this. I should try to find some time in near future develop it further. I'm still happy to receive feedback about the project and hopefully this feedback will help me to motivate to put more time on this project.
Br, petrinm

**Comment by ghost** [comment]
Thank you!  Now it builds OK.
I am planning to use this to get frequency locking on the QO-100 satellite.  I receive the satellite with GQRX but because of the high frequency (10489 MHz) any small frequency error is a problem when receiving SSB etc.
So my plan is to have a bit of gnuradio companion code receiving a fixed frequency beacon on the satellite and tune the frequency of GQRX accordingly via API.
This allows me to develop this code independently from GQRX and maybe later submit it for inclusion in the main program.
